// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdvXRmXOK7N8osGoh3DoMI6XFaov3zgUc',
    appId: '1:803971522773:web:edf0336f3a5cbd00a7025c',
    messagingSenderId: '803971522773',
    projectId: 'urban-tutor-99377',
    authDomain: 'urban-tutor-99377.firebaseapp.com',
    storageBucket: 'urban-tutor-99377.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY1nkeLXFY7uBh7kTm6kfapmzwmM6pUcY',
    appId: '1:803971522773:android:388da5f9a4d10175a7025c',
    messagingSenderId: '803971522773',
    projectId: 'urban-tutor-99377',
    storageBucket: 'urban-tutor-99377.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALzN7sqEZAHc585gm39eT3KoHBWojwatU',
    appId: '1:803971522773:ios:c869ce8d8419d1b8a7025c',
    messagingSenderId: '803971522773',
    projectId: 'urban-tutor-99377',
    storageBucket: 'urban-tutor-99377.firebasestorage.app',
    iosBundleId: 'com.example.urbanTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALzN7sqEZAHc585gm39eT3KoHBWojwatU',
    appId: '1:803971522773:ios:c869ce8d8419d1b8a7025c',
    messagingSenderId: '803971522773',
    projectId: 'urban-tutor-99377',
    storageBucket: 'urban-tutor-99377.firebasestorage.app',
    iosBundleId: 'com.example.urbanTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdvXRmXOK7N8osGoh3DoMI6XFaov3zgUc',
    appId: '1:803971522773:web:a2e8795ca3fff240a7025c',
    messagingSenderId: '803971522773',
    projectId: 'urban-tutor-99377',
    authDomain: 'urban-tutor-99377.firebaseapp.com',
    storageBucket: 'urban-tutor-99377.firebasestorage.app',
  );
}
